# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_position.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(226, 133)

        self.formBox = QtWidgets.QGroupBox("formBox")
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")

        self.edit_name = QtWidgets.QLineEdit(Dialog)
        self.edit_name.setObjectName("edit_name")
        self.formLayout.addRow(QtWidgets.QLabel("name"), self.edit_name)

        self.edit_surname = QtWidgets.QLineEdit(Dialog)
        self.edit_surname.setObjectName("edit_surname")
        self.formLayout.addRow(QtWidgets.QLabel("surname"), self.edit_surname)

        self.edit_date = QtWidgets.QDateEdit(Dialog)
        self.edit_date.setObjectName("edit_date")
        self.formLayout.addRow(QtWidgets.QLabel("birth date"), self.edit_date)

        self.edit_position = QtWidgets.QLineEdit(Dialog)
        self.edit_position.setObjectName("edit_position")
        self.formLayout.addRow(QtWidgets.QLabel("position id"), self.edit_position)

        self.edit_insurance = QtWidgets.QLineEdit(Dialog)
        self.edit_insurance.setObjectName("edit_insurance")
        self.formLayout.addRow(QtWidgets.QLabel("insurance id"), self.edit_insurance)

        self.edit_location = QtWidgets.QLineEdit(Dialog)
        self.edit_location.setObjectName("edit_location")
        self.formLayout.addRow(QtWidgets.QLabel("location id"), self.edit_location)

        self.formBox.setLayout(self.formLayout)

        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)

        mainLayout = QtWidgets.QVBoxLayout()
        mainLayout.addWidget(self.formBox)
        mainLayout.addWidget(self.buttonBox)
        Dialog.setLayout(mainLayout)

        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add worker"))
