# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.connect_btn = QtWidgets.QPushButton(self.centralwidget)
        self.connect_btn.setObjectName("connect_btn")
        self.horizontalLayout_2.addWidget(self.connect_btn)
        self.disconnect_btn = QtWidgets.QPushButton(self.centralwidget)
        self.disconnect_btn.setObjectName("disconnect_btn")
        self.horizontalLayout_2.addWidget(self.disconnect_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.show_all_workers_btn = QtWidgets.QPushButton(self.centralwidget)
        self.show_all_workers_btn.setObjectName("show_all_workers_btn")
        self.horizontalLayout_3.addWidget(self.show_all_workers_btn)
        self.show_local_workers_btn = QtWidgets.QPushButton(self.centralwidget)
        self.show_local_workers_btn.setObjectName("show_local_workers_btn")
        self.horizontalLayout_3.addWidget(self.show_local_workers_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.show_all_preferences_btn = QtWidgets.QPushButton(self.centralwidget)
        self.show_all_preferences_btn.setObjectName("show_all_preferences_btn")
        self.horizontalLayout_4.addWidget(self.show_all_preferences_btn)
        self.show_local_preferences_btn = QtWidgets.QPushButton(self.centralwidget)
        self.show_local_preferences_btn.setObjectName("show_local_preferences_btn")
        self.horizontalLayout_4.addWidget(self.show_local_preferences_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setObjectName("clear_btn")
        self.verticalLayout.addWidget(self.clear_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connect_btn.setText(_translate("MainWindow", "Connect"))
        self.disconnect_btn.setText(_translate("MainWindow", "Disconnect"))
        self.show_all_workers_btn.setText(_translate("MainWindow", "Show all workers"))
        self.show_local_workers_btn.setText(_translate("MainWindow", "Show local workers"))
        self.show_all_preferences_btn.setText(_translate("MainWindow", "Show all preferences"))
        self.show_local_preferences_btn.setText(_translate("MainWindow", "Show local preferences"))
        self.clear_btn.setText(_translate("MainWindow", "Clear"))
